server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: xxxx@qq.com
    password: xxxx
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
face:
  baidu:
    appid: 35688401
    key: xxx
    secret: xxx
